import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';

// Inject precache manifest generated by Webpack
precacheAndRoute(self.__WB_MANIFEST);

// Cache first strategy for images
registerRoute(
  ({ url }) => url.origin === 'https://example.com' && url.pathname.endsWith('.png'),
  new CacheFirst()
);

// Network first strategy for API requests
registerRoute(
  ({ url }) => url.origin === 'https://api.example.com',
  new NetworkFirst()
);